base:
  debug: true
  directories:
    base: .
    temp: temp
    data: data
    driver: temp/driver

translation:
  default_provider: alibaba
  providers:
    google:
      enabled: true
      api_key: null
      priority: 1
    bing:
      enabled: true
      api_key: null
      priority: 2
  timeout: 10
  retry: 3
  multiple:
    mode: batch
    batch_size: 10
    max_workers: 4
    timeout_per_text: 5
curency:
  alphavantage_api_key: 3DZJ2PEPJ59TV5W7
  alphavantage_url: https://www.alphavantage.co
  provider: "alpha_vantage" # atau "ecb"
  refresh_interval: 900 # 15 menit

currency_conversion:
  max_retries: 3
  retry_delay: 2
  fallback_order: ["alphavantage", "xe"]